name: Daily Tuchtrecht Sync

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run fetch script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
      run: python fetch_tuchtrecht.py
