# .github/workflows/crawl.yml
# This workflow automates the process of crawling the Tuchtrecht repository.

name: Tuchtrecht Crawler

on:
  # Allows manual triggering of the workflow from the Actions tab in GitHub.
  workflow_dispatch:
  # Schedules the workflow to run at 02:00 on every Sunday.
  schedule:
    - cron: '0 2 * * 0'

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        run: python crawler/main.py

      - name: Commit and push if it changed
        run: |
          git config --global user.name "Tuchtrecht Crawler Bot"
          git config --global user.email "crawler-bot@users.noreply.github.com"
          git add data/ .last_update
          # Commit only if there are changes
          git diff --staged --quiet || git commit -m "Weekly Tuchtrecht data update"
          git push
