name: Weekly Tuchtrecht Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # every half an hour
  workflow_dispatch:  # also allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_DATASET_REPO: vGassen/Dutch-Open-Data-Tuchrecht-Disciplinary-Court-Cases
      HF_PRIVATE: "false"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml datasets tqdm

      - name: Run scraper
        run: python main.py
