name: Fetch Tuchtrecht Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python fetch_tuchtrecht.py

      - name: Commit new data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/*.xml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update tuchtrecht data"
            git push
          fi
