name: Crawl & publish tuchtrecht

on:
  workflow_dispatch:            # manual trigger
  schedule:
    - cron: '37 2 * * *'        # daily, off‑peak (02:37 UTC)

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write            # to commit / push visited.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO:  ${{ secrets.HF_REPO }}
        run: python fetch_tuchtrecht.py --limit 5000

      - name: Commit progress artefacts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add visited.txt || true
          git diff --cached --quiet || git commit -m "Update dataset ($(date -u))"
          git push
