# .github/workflows/scrape.yml

name: Scrape and Push to Hugging Face

on:
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 8am UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy pandas huggingface_hub

    - name: Run scraper and push to HF
      run: python scrape_and_push.py
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
