name: Push 50 Tuchtrecht Cases to Hugging Face

on:
  workflow_dispatch:

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests huggingface_hub

      - name: Run upload script
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          python upload_50_to_huggingface.py
