name: Tuchtrecht Sync

on:
  schedule:
    - cron: '0 * * * *'   # Runs every hour
  workflow_dispatch:       # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests huggingface_hub

      - name: Run fetch script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python fetch_tuchtrecht.py
